#

# You can check out the STAN manual for a full list of
# possible distributions. Some common examples are given below.

# Currently supported prior distributions:
# exponential, normal, uniform.


# Note that starting values are drawn from the prior distributions,
# so improper priors might cause problems in model fitting.

# Explanation of Parameters
center: normal(350, 150)
width: normal(20, 100)
pmin: uniform(0, 0.2)
pmax: uniform(0.8, 1)
deltaL: exponential(0.05)
deltaR: exponential(0.05)
deltaM: exponential(0.05)
tauL: uniform(0, 1)
tauR: uniform(0, 1)
tauM: uniform(0, 1)
f: uniform(0,1)
